"""rag data enrichment schema

Revision ID: 101be584c190
Revises: dabce485b826
Create Date: 2026-05-16 16:41:53.377788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '101be584c190'
down_revision: Union[str, Sequence[str], None] = 'dabce485b826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('games_steam_tags',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['steam_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'tag_id')
    )
    op.create_index('idx_games_steam_tags_tag_id', 'games_steam_tags', ['tag_id'], unique=False)
    op.add_column('games', sa.Column('steam_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('steam_owners_min', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('steam_owners_max', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('steam_players_2weeks', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('steam_ccu', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('steam_metrics_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('games', 'steam_reviews_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('steam_reviews_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('games', 'steam_metrics_updated_at')
    op.drop_column('games', 'steam_ccu')
    op.drop_column('games', 'steam_players_2weeks')
    op.drop_column('games', 'steam_owners_max')
    op.drop_column('games', 'steam_owners_min')
    op.drop_column('games', 'steam_signals')
    op.drop_index('idx_games_steam_tags_tag_id', table_name='games_steam_tags')
    op.drop_table('games_steam_tags')
    op.drop_table('steam_tags')
    # ### end Alembic commands ###
