"""add_sync_state_and_ingestion_hash

Revision ID: 5d0f488ae8c7
Revises: 8d4212ab31eb
Create Date: 2026-04-21 12:36:23.645401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0f488ae8c7'
down_revision: Union[str, Sequence[str], None] = '8d4212ab31eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_state',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.add_column('games', sa.Column('ingestion_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'ingestion_hash')
    op.drop_table('sync_state')
    # ### end Alembic commands ###
