"""initial

Revision ID: 8d4212ab31eb
Revises: 
Create Date: 2026-04-21 11:30:37.119350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '8d4212ab31eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('game_modes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('igdb_rating', sa.Float(), nullable=True),
    sa.Column('metacritic_score', sa.SmallInteger(), nullable=True),
    sa.Column('steam_description', sa.Text(), nullable=True),
    sa.Column('steam_reviews_summary', sa.Text(), nullable=True),
    sa.Column('steam_score', sa.SmallInteger(), nullable=True),
    sa.Column('hltb_main', sa.Float(), nullable=True),
    sa.Column('hltb_extra', sa.Float(), nullable=True),
    sa.Column('hltb_completionist', sa.Float(), nullable=True),
    sa.Column('opencritic_score', sa.SmallInteger(), nullable=True),
    sa.Column('opencritic_excerpts', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('rawg_id', sa.Integer(), nullable=True),
    sa.Column('steam_id', sa.Integer(), nullable=True),
    sa.Column('hltb_id', sa.Integer(), nullable=True),
    sa.Column('opencritic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hltb_id'),
    sa.UniqueConstraint('igdb_id'),
    sa.UniqueConstraint('opencritic_id'),
    sa.UniqueConstraint('rawg_id'),
    sa.UniqueConstraint('steam_id')
    )
    op.create_index('idx_games_title', 'games', ['title'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('preferred_playtime', sa.Enum('short', 'medium', 'long', name='playtime_preference'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('game_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'model_version', name='uq_game_embeddings_game_model')
    )
    op.create_index('idx_game_embeddings_game_id', 'game_embeddings', ['game_id'], unique=False)
    op.create_table('games_genres',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    op.create_index('idx_games_genres_genre_id', 'games_genres', ['genre_id'], unique=False)
    op.create_table('games_modes',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mode_id'], ['game_modes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'mode_id')
    )
    op.create_index('idx_games_modes_mode_id', 'games_modes', ['mode_id'], unique=False)
    op.create_table('games_platforms',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'platform_id')
    )
    op.create_index('idx_games_platforms_platform_id', 'games_platforms', ['platform_id'], unique=False)
    op.create_table('games_tags',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('game_id', 'tag_id')
    )
    op.create_index('idx_games_tags_tag_id', 'games_tags', ['tag_id'], unique=False)
    op.create_table('user_favorite_genres',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'genre_id')
    )
    op.create_table('user_games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('playing', 'completed', 'backlog', 'dropped', name='user_game_status'), nullable=True),
    sa.Column('user_rating', sa.SmallInteger(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('hours_played', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('user_rating BETWEEN 1 AND 10', name='ck_user_games_rating'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_games_user_game')
    )
    op.create_index(op.f('ix_user_games_game_id'), 'user_games', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_games_user_id'), 'user_games', ['user_id'], unique=False)
    op.create_table('user_important_criteria',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'criterion_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('user_important_criteria')
    op.drop_index(op.f('ix_user_games_user_id'), table_name='user_games')
    op.drop_index(op.f('ix_user_games_game_id'), table_name='user_games')
    op.drop_table('user_games')
    op.drop_table('user_favorite_genres')
    op.drop_index('idx_games_tags_tag_id', table_name='games_tags')
    op.drop_table('games_tags')
    op.drop_index('idx_games_platforms_platform_id', table_name='games_platforms')
    op.drop_table('games_platforms')
    op.drop_index('idx_games_modes_mode_id', table_name='games_modes')
    op.drop_table('games_modes')
    op.drop_index('idx_games_genres_genre_id', table_name='games_genres')
    op.drop_table('games_genres')
    op.drop_index('idx_game_embeddings_game_id', table_name='game_embeddings')
    op.drop_table('game_embeddings')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('platforms')
    op.drop_table('genres')
    op.drop_index('idx_games_title', table_name='games')
    op.drop_table('games')
    op.drop_table('game_modes')
    op.drop_table('criteria')
    # ### end Alembic commands ###
