"""add_igdb_enriched_fields

Revision ID: a9455454548f
Revises: 5d0f488ae8c7
Create Date: 2026-04-22 06:24:51.805410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9455454548f'
down_revision: Union[str, Sequence[str], None] = '5d0f488ae8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('storyline', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('igdb_rating_count', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('igdb_updated_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'keywords')
    op.drop_column('games', 'igdb_updated_at')
    op.drop_column('games', 'release_date')
    op.drop_column('games', 'igdb_rating_count')
    op.drop_column('games', 'storyline')
    # ### end Alembic commands ###
