"""add_message_proposals

Revision ID: c7edc7987d27
Revises: 9f7a2c6b4d1e
Create Date: 2026-05-09 01:53:14.879189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7edc7987d27'
down_revision: Union[str, Sequence[str], None] = '9f7a2c6b4d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('add_to_library', 'change_status', 'set_rating', 'remove_from_library', name='proposal_action_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('pending', 'confirmed', 'cancelled', name='proposal_state'), server_default='pending', nullable=False),
    sa.Column('state_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_proposals_message_id'), 'message_proposals', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_proposals_message_id'), table_name='message_proposals')
    op.drop_table('message_proposals')
    # ### end Alembic commands ###
